env:
  global:
    - TERM=dumb
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - JDK="adopt@1.11"
    - secure: "Kcqxi5Sdqo+lBMUuZGXUDvDlJmgkL8HQ/lrliFeo1PTvSNCBRh6us/lOcEXBMRKvOcn+bfMMk0UZyrA5VqHOdFeUMiCgPLiQ53v5wMVPtpol550suclc+Mb5CkBAwnQzgXlPoTN5pjlf1n1SJaqH+ebnTaJeMEMCdF8XtzMZnyGrrksEtnudBp6TSITBQ2aFOoJcJcOxB39kebJ7drbDcFLbpYdESFsTnfsO7sTjPwqehBZJjgtZLelSWjti2cAhp65Hj0dnfhauykNHzoTGc3vDswDvnLK9I9L/pDmkJyUSyWjC0e/JfAeRV+Gtjuy0l8kjHb0V2ien4DEAp1VLsTmKx70jriWQfk/TcMTJzE+xbEIkoKTavScqosCe99xgJvROMNNE2llwewnWnHqMynGsxxAp1QW9nLBLUacwV/W9Q3F9ysoaRfJL9ndSH04UA27w76Wie9YuQztbcTPN3CQQqmFKy7FL/YxoFZfMC5zBrt13wHP+URyAcVoxFhkDREXXvNmTmQDPUuju+ZSbyv/Tk2VryUPy8J9hecgU7w+gSaQGLkjO2nMA07PXFMQSrRvXkl49gWv9uYb+of6GGBUsyF5vdg4f6Ey739/NvBWU7gBVN4XvZ/hrld0cxcqlnN8lB3XJ/iimnTkc9zvx5FbXl7h7jxFPmCOshs6WRbs="

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk

before_deploy:
  - git config --local user.name "w4bo"
  - git config --local user.email "m.francia@unibo.it"
  - $GRAVIS/autotag

language: ruby

rvm:
  - 2.6.3

before_script:
  - chmod +x build.sh

cache: bundler

script: 
  - ./build.sh
  - cd _site
  - zip -r ../big-website.zip *
  - cd ..
  - ls

deploy:
  provider: releases
  api_key:
    secure: "mGhTwyQeMpRkmPG/06SbqzqBG+p4pBxTmI8eTII/NjHsP7MrpN/SukIiC1LhziV0AW4QA0Wl9smtf+km1rl5r5gvrhFVFz75UVcRQF8/1A8RQ39GOtk+YIQ/FP8ceI0MQdqkCiTbRS/5tbK+magej8KWrQUd0AeG0UfmTXLJROBNmeEZFZSTRQXvtJ2N0nREfkFhS6YqQMVBG4JOM6s+6u1Q4g2elY9VLUR0vrlrB6wAZg236P9x8G5Y8g+GIH/PV+FbLuOpbjlvr+PtVjOYk+NxrbhSVZqqL/2CQcYr8+B9n+MJY0q78oYEbj85FJc4dRDoFujV51ZvwyKRs+YuOixUrdMSR0s1i6BZFtkAdQ+xCm9vkY/f+WVDES+bhoGHRhHedv/Il5WELkwezU0dVyKR6XwNmbdQMlf/whaaao4EgMJcGmXIk59RrL2EdsSBW+MjMfs3wSRNAUuTQCEnfemToyiNEV6RZKHMya8EWJYiuj5RGLgYGoHhZa/GbhSDzem9HrIliuFWCbcwGioqPnf+8ipra0A3PMY928lpRukievmtCFdOYvPyJHCKBFNnllmgAWSEqTSzVNJilCE8xwrTdFwVt6TwjQuLusrUg8d7FJUeTBTmEBc8J28j51WS8W0rjMagYoIfViNMI05/mh9p6H24jVe8C1mV+chlg98="
  skip_cleanup: true
  file_glob: true
  file: "*.zip"
  on:
    all_branches: true
    tags: false

notifications:
  email:
    on_success: never