language: ruby

rvm:
  - 2.6.3

before_script:
  - chmod +x build.sh

cache: bundler

script: 
  - ./build.sh
  - cd _site
  - zip -r ../big-website.zip *
  - cd ..
  - ls

deploy:
  provider: releases
  api_key:
    secure: "UBz6Y9LFVbzlzDc1bicaHSYnq/Ia4nitEqa0c47Ze9Y41lanCSb4FLJhpUQIPB7tKB7xYzjqWEt5xvwHxQgBcJgf0FI34kvaVuH9a/kXQ993e1VUZhF/kfZ7IyecBImOP2+nkWGd+quoy86mX4bCN3Cuq2h+M4UoSSZOvMT9VY6mxy0qiF+3ICzC69ZUcqLDGgGeRmT57DJX61GbTk/vwNXHEy8YX9GKnSN7MfbP8S0nJPXvAT6TgyNg/dsHgUgR8neODvEgWPa/fG2YbD/411GzE+oaJk1sc6CxHqY6a5wQBajL/Zkbo5xHKXWplexmcXevMuOtHRNdJNGutOLHinEkpx0zJMaAXgdBX4ZOSe7GkdoyPEwat4COZeIdx5VlI9gedN5mAiMGKMuilN+alD7g/5RC/DGfe2oyXm9GdC2IrlU4WA+ipuaoA9FECqBcyCrkz2npZi9t8ZsmilzWso540akbeWp/ucmSxy+Uxy2KJ3jDd+7BLzgFjCDoabwhhlbXiTnSWT6QX+WNzMyV8BXX1eKhVM/YrYX4Vdv28MtHi2C8UvKzLkoBLfyrD0Ak02ptEWZkGlxBP8j53jsidgNdYIJXqoUZuYhUsZFg+4xQB3c0iGIOL0L995BrIdRYRpVdetXZE2cBcWcv8vl1sJHtdgt3JIDmtoTpWKXjqQQ="
  skip_cleanup: true
  file_glob: true
  file: "*.zip"
  on:
    all_branches: true
    tags: false

notifications:
  email:
    on_success: never